### ISSUE TITLE
v0.2 protocol question 

### ISSUE THREAD

**Issue by Zepan** [JiriBilek/WiFiSpiESP#10]
Glad to see v0.2 protocol released! 
I have tested v0.1 before, just want know how does v0.2 promote.
v0.1 have 4byte status msg, and need at least 20us CS low before send data, and SPI freq should below 9MHz, the wifi speed test I get about 100KB/s maximum.
v0.2 have shortr 2byte status msg in description, does it also improve max SPI freq and shorter CS low time? What the max wifi speed can v0.2 reach?

**Comment by JiriBilek** [comment]
Hi,
regarding the speed of communication, the situation didn't change too much. The two bytes of status spared are virtually nothing compared to 32 byte data messages running between master and slave.

I didn't find how to fix the 20us delay after putting SS down. However strange it seems to me that ESP8266 needs some time to accept the clock. Without the delay it occurred that several clock cycles were lost, the slave read bad value and the communication was therefore corrupted.

My testing setup includes 9 MHz SPI clock on STM32F103, too. I haven't tried a faster speed yet. I am afraid, the bottleneck is in the obligatory length 32 byte data message. 

Thanks for testing the library.

**Comment by Zepan** [comment]
Hi, I have also test an commerce esp8266 spi module,  speed is up to 1.5MB/s@27MHz SPI clock.
I capture the wave, it have very short CS low time, and still use 32byte data msg.
In my opinion, bottleneck is:  CS low time 30%, SPI CLK speed 70%.
And I'm trying to reverse that firmware, maybe I can figure it out.

**Comment by JiriBilek** [comment]
I would be particularly interested in setup procedure, i.e. what is written to ESP8266 registers on init.
