### ISSUE TITLE
Error processing long commands

### ISSUE THREAD

**Issue by a7o** [JiriBilek/WiFiSpiESP#17]
I tried to use the app together with the WifiWebClient example sketch, using the WiFiSpi library on STM32F4. In general it does work, but there is an obvious error in the WiFiSPICmd module when processing long commands (with the MESSAGE_CONTINUES tag). My home WiFi SSID and password are long enough, so the "Set passphrase" command with all the attributes is longer than 32 bytes, and it doesn't work - the second 32-byte packet from the STM32 is treated as a new command.

**Comment by JiriBilek** [comment]
Hi, 
thanks for reporting an issue. For speeding up the fix could you please post an example?

**Comment by a7o** [comment]
On ESP, I used your sketch; on STM - the WiFiClient example sketch with your WiFiSPI library, with adding only my SSID and password.

**Comment by a7o** [comment]
Some new information: now I compiled the sketch with no debug output, it seems to work. So I guess that the second packet simply overwrites the receive buffer when the first packet isn't processed yet due to delay caused by the Serial output. That's only my guess, of course, I haven't done deep code analysis.

**Comment by JiriBilek** [comment]
Thanks a lot, I'll look at it tomorrow, I have to set up my testing hardware first. A quick look at the code haven't shown a bug.

**Comment by JiriBilek** [comment]
I tried with both _DEBUG and _DEBUG_MESSAGES set and it works except the case when the SSID is 32 characters long. But it doesn't work regardless of debug settings, it may be a bug outside of my code.
Could the 32 byte SSID be your problem, too?

Could you please add to `WiFiSpiCmdConnection.cpp`, after line 73 the following code and see if it reports the SSID and password correctly?
`Serial.printf("Wifi.begin, ssid=%s, pwd=%s\n", ssid, passphrase);`

My dump:
```
SPI SLAVE ver. 0.2.4
Protocol ver. 0.2.4
<< df e0 20  0 ee  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 8a
>> df e0 a0  1  1  6 ee  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
<< df e0 50  0 ee  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 7e
>> df e0 d0  1  5 30 2e 32 2e 34 ee  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
<< dc e0 11  2 20 42 49 4c 4e 65 74 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 32 30 2d 2d 2d 2d 2d 2d 97
<< dc 2d 2d 2d 2d 33 32 20 50 6c 38 6e 69 34 6b 6f 76 61 2b 2b 2b 2b 2b 2b 2b 2b 32 30 2d 2d 2d a9
<< df 2d 2d 2d 2d 2d 2d 2d 33 32 ee  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 27
Wifi.begin, ssid=TSTNet------------20----------32
Wifi.begin, ssid=TSTNet------------20----------32, pwd=PPPPPPPPPP++++++++20----------32
mode : sta(a0:20:a6:04:a5:8b)
add if0
```

**Comment by a7o** [comment]
Oops, it looks like my fault. I uncommented also _DEBUG_SPICALLS, which could cause unacceptable delays in the SPI messages processing. Now it seems to work with my SSID and password (each of them doesn't exceed 32 bytes, but together they are). Sorry to bother you.

**Comment by JiriBilek** [comment]
No worries, I am glad it works :)
Closing.
