### ISSUE TITLE
class BearSSL::WiFiClientSecure' has no member named 'verify'

### ISSUE THREAD

**Issue by nopnop2002** [JiriBilek/WiFiSpiESP#18]
Hello.

I changed WiFiSPICmdClient.cpp:
```
//#include <WiFiClientSecureAxTLS.h>
#include <WiFiClientSecureBearSSL.h>
```

But i get compile fail.

```
'class BearSSL::WiFiClientSecure' has no member named 'verify'
```

Do you have any solution?

**Comment by JiriBilek** [comment]
Yes, check out the BearSSL branch of the repository.

**Comment by nopnop2002** [comment]
Thank you.
The compilation was successful.

>Yes, check out the BearSSL branch of the repository.

Please include this in the README.

**Comment by JiriBilek** [comment]
I'd better merge the branch into the master trunk asap. Thanks for the feedback.
