### ISSUE TITLE
Safe reset using external circuit

### ISSUE THREAD

**Issue by JiriBilek** [JiriBilek/WiFiSpiESP#6]
Add the option to sort out the reset problem.
When ESP resets, it reads GPIO15 and when HIGH, it doesn't boot from flash, but from the SDIO instead.
A circuit can be made that solves it using another GPIO to enable the GPIO for input after boot.
See https://github.com/esp8266/Arduino/issues/2466#issuecomment-330322176
The picture as it was published in the mentioned thread:

![30559281-62cbffba-9cb4-11e7-81f7-3fe89bb99381](https://user-images.githubusercontent.com/15474360/36410501-9f72c38c-1611-11e8-8287-6f5233012638.jpg)

**Comment by jandrassy** [comment]
If someone plans to produce an esp8266 SPI shield, it should have this

**Comment by JiriBilek** [comment]
The circuit built and tested. Closing the issue.
