### ISSUE TITLE
Spi Slave data transfer information

### ISSUE THREAD

**Issue by prateek027** [JiriBilek/WiFiSpiESP#7]
Hi,
I just know the few things about the spi slave data transfer.
i am follow your library and need some information about the library (SPI Slave in NodeMcu ESP8266

1- What is the SPI Mode you are using.
2- what is the Data Rate you are using.
3- what is the clock configuration.
4- master Sends 16 Byte Data length  for 10 Times but it only receive 3 Strings of 16 Bytes in which 11 Bytes are correct rest 5 Not.
5- if I need to Receive only 4 or Less than 4 Bytes in One time then where i can change for receive correct  Data.

**Comment by JiriBilek** [comment]
Hi,

1. The mode is MSBFIRST, SPI_MODE0 in Arduino's terminology. You can check it out in the library for the other side of the communication channel ([WiFiSpi-wifispi_drv.cpp](https://github.com/JiriBilek/WiFiSpi/blob/a544d9316d8b10e52a9aca434e0ae3c254c20c61/src/utility/wifispi_drv.cpp#L137)). I used this setting because it worked for me and I couldn't find any information about SPI registers of 8266 MCU.
2. The data rate is controlled by master. My tests using STM32F103 as master run on 2.25 MHz.
3. I don't understand the question.
4. and 5. Without knowing of your setup I can tell nothing.

The only documentation about SPI interface in 8266 I found in [esp8266.peri](https://github.com/esp8266/Arduino/blob/18f643c7e2d6a0da9d26ff2b14c94e6536ab78c1/cores/esp8266/esp8266_peri.h#L296). Maybe it is possible to tweak the setup and transfer other amounts of data, but without detailed documentation it would be a waste of time.
This app and a library for the master side started from existing applications so I didn't have to worry about all the 8266 register setup.

**Comment by prateek027** [comment]
Thanks for the reply Jiri, 
Pardon my English, the whole scenario is look like this - 

Master <--SPI--> NodeMCU   

I need sensor data from master which comes in chunks of 16 bytes like(can make it 32 also) 
what i send - " 01 02 03 04 05 06 07 08 09 A0 B0 C0 D0 E0 F0 10 "

what i am getting  - " 03 04 05 06 07 08 09 A0 B0 C0 D0 00 FF 00 "
First two byte i.e " 01 02 "are missing in receiving  and the last 3 bytes(E0 F0 10)  recevied as 00/FF or random   

let us say master sends these type of total 10 byte array one by one 
out of 10 these array i receive only two array( 2nd and 6th) rest of the byte array are missing.
as you mentioned in reply i am also using SPI_Mode0 and MSB First on master side. 
 
Thanks in advance

**Comment by JiriBilek** [comment]
The SPI message received by slave SPI interface has to have the fixed format (see [espspi_proxy.h](https://github.com/JiriBilek/WiFiSpi/blob/master/src/utility/espspi_proxy.h)):

- first byte is a command code (**01** - write status, **02** - write data, **03** - read data, **04** - read status)

- for status messages 4 bytes of the status follow

- for data messages one byte of **00** follows (dummy, don't know what it means) and then the 32 bytes of the data (the payload).

It seems to me that your first byte was taken as the command, the second was ignored and the following 14 bytes were read correctly. The last two bytes came from whatever source.

Try to start the message with two bytes **02** **00**, and then your 16 bytes of payload. It should work.
Jiri

**Comment by prateek027** [comment]
Hi,
Thanks for reply.
So, you want to say that i just add two bytes (0x02 0x00) before sending data to slave.

**Comment by JiriBilek** [comment]
Exactly :)

**Comment by prateek027** [comment]
You know what, you just saved me !!
Much appreciated, thanks for the favor.. :)

**Comment by JiriBilek** [comment]
You're welcome, I was glad to be able to help you.

**Comment by prateek027** [comment]
Hi Jiri,
Please Let me know that is any status bytes when i send data from slave to master. 
just like i need to send Data like 0x01 0x01 0x01 0x01 0x0C 0x0D to master.
when i generate a request from master to slave for data Transfer, i get Exception 3. 
what can i do.

**Comment by prateek027** [comment]
Hi Jiri, can you help me for sending data, i am stuck here.

**Comment by JiriBilek** [comment]
HI,
sending data back (4 bytes of "status") you can use [hspi_slave_setStatus](https://github.com/JiriBilek/WiFiSpiESP/blob/19f3338cb7353d4934895484e22058c28aa6d55e/WiFiSPIESP/hspi_slave.c#L101) function. ON the master side you initiate the transfer as in [readStatus](https://github.com/JiriBilek/WiFiSpi/blob/a544d9316d8b10e52a9aca434e0ae3c254c20c61/src/utility/espspi_proxy.h#L107) function.

I believe that master sends one byte (04 - read status command) and then reads 4 bytes. The slave side is 
quite simple:

```
void ICACHE_RAM_ATTR hspi_slave_setStatus(uint32_t status)
{
    SPI1WS = status;
}
```

**Comment by prateek027** [comment]
Hi Jiri, on the master side i am using nrf52 and send like this 
 
uint8_t status[2] = {0x03,0x00};
ret = nrf_drv_spi_transfer(&spi2, status, 2, rxBuf,4);


On slave side i am setting like this 
 SPISlave.onData([](uint8_t * data, size_t len) 
{
 uint8_t ans[] = {0x03,0x00,0x01,0x01,0x01};
 if(data[0] == 0x01 && data[1] == 0x01 && data[2] == 0x01)
 {
    SPISlave.setData(ans,sizeof(ans));
  }     
 });  

SPISlave.onDataSent([]() {
    #ifdef _DEBUG    
      Serial.println("Data sent");
    #endif        
    }
    );

what exactly i needed is only to send master a simple ACK(byte string) which it can read and confirm about the data has been transferred over wifi, till the last receiving.

**Comment by JiriBilek** [comment]
I am afraid you are mixing data output and status output. The command **03** requires 16 bytes of data (similarly to **02**). Your code attempts to read after the buffer (array ans[]) and that could cause exception.
I suggest you to try to extend the ans[] array to 32 bytes and try it once more.
Another possibility is to use command 04 (read status) and transfer only 4 bytes of "status".
Please look at the source code I pointed you at in my previous post.
J.

**Comment by prateek027** [comment]
Thanks for the reply Jiri , 
i tried with ans[] to extend 32 bytes and checked but no luck. 
ok i will try to send only 4 bytes and checking the code pointed by you.

**Comment by prateek027** [comment]
HI Jiri,
as you mention in previous comments. 
i have extend the ans[] array to 32 bytes and send to master.

from master side i receive data like this.
uint8_t status[2] = {0x03,0x00};
uint8_t status[1] = {0x00};
   nrf_drv_spi_transfer(&spi2, status, 2, NULL,0);  -- first send the cmd to receive the data as mention in masterSPI code.
   ret = nrf_drv_spi_transfer(&spi2, status2, 1, rxBuf,32); -- after that i send 00 first and receive the 32 bytes from slave.
-----------
In slave side i used function like this.
uint8_t ans[] = {0x01,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x00,0x00};

SPISlave.onData([](uint8_t * data, size_t len)
{
if(data[0] == 0x01 && data[1] == 0x01 && data[2] == 0x01)
{
SPISlave.setData(ans,sizeof(ans));
}
});

SPISlave.onDataSent( {
#ifdef _DEBUG
Serial.println("Data sent");
#endif
}
);
after doing this i am getting 00 00 00 00 00 00 00 ... upto 32 bytes on master side.
currently i am not using status bytes to send the receive. any next update in my issue?

**Comment by prateek027** [comment]
HI Jiri,
as you mention in previous comments. 
i have extend the ans[] array to 32 bytes and send to master.

from master side i receive data like this.
uint8_t status[2] = {0x03,0x00};
uint8_t status[1] = {0x00};
   nrf_drv_spi_transfer(&spi2, status, 2, NULL,0);  -- first send the cmd to receive the data as mention in masterSPI code.
   ret = nrf_drv_spi_transfer(&spi2, status2, 1, rxBuf,32); -- after that i send 00 first and receive the 32 bytes from slave.
-----------
In slave side i used function like this.
uint8_t ans[] = {0x01,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x03,0x00,0x01,0x01,0x01,0x00,0x00};

SPISlave.onData([](uint8_t * data, size_t len)
{
if(data[0] == 0x01 && data[1] == 0x01 && data[2] == 0x01)
{
SPISlave.setData(ans,sizeof(ans));
}
});

SPISlave.onDataSent( {
#ifdef _DEBUG
Serial.println("Data sent");
#endif
}
);
after doing this i am getting 00 00 00 00 00 00 00 ... upto 32 bytes on master side.
currently i am not using status bytes to send the receive. any next update in my issue?

**Comment by JiriBilek** [comment]
Your slave should set 32 bytes of data as in your onData function first (maybe as a result of another SPI communication...)
Your master should send 03 00 and then read 32 bytes of data.

**Comment by prateek027** [comment]
Hi Jiri, i have done changes as mentioned by you, but still i am getting zeros only on master side.

**Comment by JiriBilek** [comment]
I am sorry, I can't help you more. Not knowing even a little about your code I am led to guess what to do.

**Comment by prateek027** [comment]
No worries, i am sharing the code (slave)
//
#include "SPISlave.h"
#include <ESP8266WiFi.h>

uint8_t ans[34] = {0x01,0x00,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x010x01,0x01};
#define _DEBUG
void setup()
{
  SPISlave.begin();
    Serial.begin(115200);

#ifdef _DEBUG    
    Serial.setDebugOutput(true);
#endif


     // --- onData
    // Data has been received from the master. Beware that len is always 32
    // and the buffer is autofilled with zeroes if data is less than 32 bytes long
    SPISlave.onData([](uint8_t * data, size_t len) {
    #ifdef _DEBUG    
      Serial.print("gotData ");
      //for (uint8_t i=0; i<len; ++i)
       // Serial.printf("%02x ", data[i]);
       // Serial.println();
        if(data[0] == 0x01 && data[1] == 0x01 && data[2] == 0x01)
        {
          Serial.println("Hello master");
        }
    #endif        
    });

    // --- onDataSent
    // The master has read out outgoing data buffer
    // that buffer can be set with SPISlave.setData
    SPISlave.onDataSent([]() {
    #ifdef _DEBUG    
      Serial.println("Data sent");
    #endif        
    });
    
}
void loop() {}
//

and for Master Side 
//
uint32_t spi2Read(uint8_t *rxBuf)
{
	uint32_t ret = SPI_SUCCESS;
    uint8_t status[2] = {0x03,0x00};
	spi1TrCompleteFlag = false;
	nrf_drv_spi_transfer(&spi2, status, 2, NULL,0);
	 nrf_delay_ms(10);
	ret = nrf_drv_spi_transfer(&spi2, NULL, 0, rxBuf,32);


	for(int i=0;i<32; i++)
	{
	  print(LL_PRINT, "%02X",rxBuf[i]);	
	}

return ret;

} 
//

**Comment by JiriBilek** [comment]
@prateek027: I can't see where you send the ans buffer (slave SPI). Also, in the ans buffer you have a typo near the end: 0x010x01

**Comment by prateek027** [comment]
Hi Jiri,
sorry for the typing mistake. the correct method i use is mention below.

uint8_t ans[] = {0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01,0x04,0x01,0x01,0x01};

void setup()
{
SPISlave.begin();
Serial.begin(115200);

#ifdef _DEBUG
Serial.setDebugOutput(true);
#endif
 // --- onData
// Data has been received from the master. Beware that len is always 32
// and the buffer is autofilled with zeroes if data is less than 32 bytes long
SPISlave.onData([](uint8_t * data, size_t len) {
#ifdef _DEBUG    
  Serial.print("gotData ");
  //for (uint8_t i=0; i<len; ++i)
   // Serial.printf("%02x ", data[i]);
   // Serial.println();
    if(data[0] == 0x01 && data[1] == 0x01 && data[2] == 0x01)
    {
      Serial.println("Hello master");
      SPISlave.setData(ans,sizeof(ans));
    }
#endif        
});

// --- onDataSent
// The master has read out outgoing data buffer
// that buffer can be set with SPISlave.setData
SPISlave.onDataSent([]() {
#ifdef _DEBUG    
  Serial.println("Data sent");
#endif        
});
}

void loop() {}

-- Master side code i have mentioned in previous post. 

-- Master sends 03 00 first and then receive 32 bytes data from slave. in rxbuf i receive only 00 00 00 .. 32 Bytes. 

-- requirement, 
1- send 01 01 01 from master to slave. then slave send 01 01 01 to master. that the only thing i can use in my program for testing after that i implement the final requirement.

**Comment by JiriBilek** [comment]
1. ensure that there is sufficient delay on master side between sending data and receiving data
2. what are you getting as serial output on slave side?

**Comment by prateek027** [comment]
1- i have check the delay from 1 ms to 10 ms but the result is same.
2- when i send data from master it receive currect data from master, and at slave.dataset[] it shows hello Master. after that is show Data send at the same time i can check in my buffer that is 00 00 00 ... 
any new thing i can in this code.

**Comment by JiriBilek** [comment]
The best would be to use a logic analyzer and see what do the signals look like.
Try to extend the master delay (e.g. 1 s) and investigate whether the "Data sent" on slave comes with the delay as well. This would check if slave is not transmitting data before the master can read it.

**Comment by prateek027** [comment]
Hi Jiri,
Thanks for your help. finally i resolved the issue.
